version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.10
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
       - kafka

  kafka:
    image: confluentinc/cp-kafka:6.2.10
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
       - kafka

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./data/postgres_data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - database


  load_trips:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UNAME: $USER
    command: jobsity load-trips
    volumes:
      - .:$HOME/app
    networks:
      - kafka
      - database
    env_file:
      - .env
    depends_on:
      - kafka
      - db


  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UNAME: $USER
    command: sleep infinity
    volumes:
      - .:$HOME/app
    networks:
      - kafka
      - database
    env_file:
      - .env

networks:
  kafka:
  database:
